# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [50]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [51]:
### [your code here]


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [52]:
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [65]:
print(a)
a.shape

[[[0.93959    0.04765256 0.5183324  0.51511665 0.34563721]
  [0.71352245 0.49483539 0.61275024 0.38406476 0.08837429]
  [0.86904217 0.38748545 0.52598365 0.68346484 0.12066035]]

 [[0.37075735 0.78812012 0.86198124 0.93734278 0.92548434]
  [0.17938894 0.04301816 0.24325894 0.19182282 0.98078453]
  [0.5144891  0.54662662 0.08880951 0.03867767 0.64480463]]]


(2, 3, 5)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [54]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [64]:
print(b)
b.shape

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)


### 7. Do a and b have the same size? How do you prove that in Python code?


In [56]:
a.shape == b.shape

False


### 8. Are you able to add a and b? Why or why not?


In [57]:
# arr_sum = a + b
# print(arr_sum)

# No, Because they are of the same shape



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [66]:
c = b.transpose(1, 2, 0)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(d)
# because they are of the same shape now

[[[1.93959    1.04765256 1.5183324  1.51511665 1.34563721]
  [1.71352245 1.49483539 1.61275024 1.38406476 1.08837429]
  [1.86904217 1.38748545 1.52598365 1.68346484 1.12066035]]

 [[1.37075735 1.78812012 1.86198124 1.93734278 1.92548434]
  [1.17938894 1.04301816 1.24325894 1.19182282 1.98078453]
  [1.5144891  1.54662662 1.08880951 1.03867767 1.64480463]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [72]:
display(a)
display(d)


array([[[0.93959   , 0.04765256, 0.5183324 , 0.51511665, 0.34563721],
        [0.71352245, 0.49483539, 0.61275024, 0.38406476, 0.08837429],
        [0.86904217, 0.38748545, 0.52598365, 0.68346484, 0.12066035]],

       [[0.37075735, 0.78812012, 0.86198124, 0.93734278, 0.92548434],
        [0.17938894, 0.04301816, 0.24325894, 0.19182282, 0.98078453],
        [0.5144891 , 0.54662662, 0.08880951, 0.03867767, 0.64480463]]])

array([[[1.93959   , 1.04765256, 1.5183324 , 1.51511665, 1.34563721],
        [1.71352245, 1.49483539, 1.61275024, 1.38406476, 1.08837429],
        [1.86904217, 1.38748545, 1.52598365, 1.68346484, 1.12066035]],

       [[1.37075735, 1.78812012, 1.86198124, 1.93734278, 1.92548434],
        [1.17938894, 1.04301816, 1.24325894, 1.19182282, 1.98078453],
        [1.5144891 , 1.54662662, 1.08880951, 1.03867767, 1.64480463]]])


### 12. Multiply a and c. Assign the result to e.


In [73]:
e = a * c
print(e)

[[[0.93959    0.04765256 0.5183324  0.51511665 0.34563721]
  [0.71352245 0.49483539 0.61275024 0.38406476 0.08837429]
  [0.86904217 0.38748545 0.52598365 0.68346484 0.12066035]]

 [[0.37075735 0.78812012 0.86198124 0.93734278 0.92548434]
  [0.17938894 0.04301816 0.24325894 0.19182282 0.98078453]
  [0.5144891  0.54662662 0.08880951 0.03867767 0.64480463]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
#Yes, Because C is all ones, so the result is the same as A



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [75]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [82]:
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]